# configs/kafka/kafka-users.yaml
# Defines only the admin user for the cluster.
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: admin-user
  namespace: kafka
  labels:
    # This label connects the user to our Kafka cluster
    strimzi.io/cluster: my-kafka-cluster
spec:
  authentication:
    type: scram-sha-512
  # Authorization is handled by listing this user as a 'super.user' in the main Kafka resource,
  # so no specific ACLs are needed here.