# configs/kafka/kafka-kraft-cluster.yaml
# This single file defines both the Kafka cluster and its required Node Pool.
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-kafka-cluster
  namespace: kafka
  annotations:
    # This enables KRaft mode (no Zookeeper).
    strimzi.io/kraft: enabled
    strimzi.io/node-pools: enabled
spec:
  kafka:
    version: "3.7.0"
    # 'replicas' and 'storage' are managed by the KafkaNodePool below
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
      - name: external
        port: 9094
        type: nodeport
        tls: false
        authentication:
          type: scram-sha-512
        configuration:
          brokers:
          - broker: 0
            advertisedHost: 127.0.0.1
            advertisedPort: 9094
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
  entityOperator:
    topicOperator: {}
    userOperator: {}
---
# The KafkaNodePool is defined in the same file to be applied atomically.
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: controller-broker
  namespace: kafka
  labels:
    # This label connects the node pool to our Kafka cluster
    strimzi.io/cluster: my-kafka-cluster
spec:
  replicas: 1
  roles:
    - controller
    - broker
  storage:
    type: ephemeral