# This resource definition ensures the 'spark-apps' namespace exists.
# Applying this file will create the namespace if it's missing.
apiVersion: v1
kind: Namespace
metadata:
  name: spark-apps
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: spark-apps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-driver-role
  namespace: spark-apps
rules:
  # The Spark driver needs to be able to create, list, and delete pods for its executors.
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "delete"]
  # It also needs to create and delete services to communicate with executors.
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "create", "delete"]
  # The driver may create ConfigMaps for sharing configuration with executors.
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-driver-role-binding
  namespace: spark-apps
subjects:
  - kind: ServiceAccount
    name: spark
    namespace: spark-apps
roleRef:
  kind: Role
  name: spark-driver-role
  apiGroup: rbac.authorization.k8s.io

